export const SCREEN_NAMES = {
  SPLASH: 'Splash',
  AUTH: 'AUTH',
  CREATE_POST: 'Create Post',
  HOME: 'Home',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  PLANS: 'Plans',
  MAIN: 'Main',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  ABOUT: 'About',
  CONTACT: 'Contact',
  FORGOT_PASSWORD: 'ForgotPassword',
  LOGIN_VERIFICATION: 'Login Verification',
  FORGOT_VERIFICATION: 'Forgot Verification',
  POSTS: 'Posts',
  CHANGE_PASSWORD: 'Change Password',
};
