export const SCREEN_NAMES = {
  SPLASH: 'Splash',
  AUTH: 'AUTH',
  CREATE_AD: 'Create Ad',
  HOME: 'Home',
  LOGIN: 'Log in',
  SIGNUP: 'Sign up',
  PLANS: 'Subscription Plans',
  MAIN: 'Main',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  ABOUT: 'About',
  CONTACT: 'Contact',
  FORGOT_PASSWORD: 'Forgot Password',
  LOGIN_VERIFICATION: 'Log in Verification',
  FORGOT_VERIFICATION: 'Forgot Verification',
  POSTS: 'Posts',
  POST_DETAILS: 'Post Details',
  CHANGE_PASSWORD: 'Change Password',
  OTP: 'OTP',
  EDIT_PROFILE: 'Edit Profile',
  PAYMENT: 'Payment',
  Terms: 'Terms & Conditions',
};
