export const SCREEN_NAMES = {
  SPLASH: 'Splash',
  AUTH: 'AUTH',
  CREATE_AD: 'Create Ad',
  HOME: 'Home',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  PLANS: 'Subscription Plans',
  MAIN: 'Main',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  ABOUT: 'About',
  CONTACT: 'Contact',
  FORGOT_PASSWORD: 'Forgot Password',
  LOGIN_VERIFICATION: 'Login Verification',
  FORGOT_VERIFICATION: 'Forgot Verification',
  POSTS: 'Posts',
  CHANGE_PASSWORD: 'Change Password',
  OTP: 'OTP',
  EDIT_PROFILE: 'Edit Profile',
};
